# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c2094a604fb99c96f0cae485e92cc9e4901246ea7eaff15893b75394ee4e9e6d572d04fc6ba9c560444736a056486b11581a260273dcb2034900b270891f74

test:
  secret_key_base: e8e32f3d440c6d5bc01255e2d7c9e344d189bfd7e194be689950f1ff1ca216793f414de0cb82f6c07febfcf13e127fd9fe303c5d0bb216b36d0299fb26cd06d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
